sc_sebastien_caumes_newwork:
    resource: "@SCSebastienCaumesBundle/Resources/config/routing/newwork.yml"
    prefix:   /admin

sc_sebastien_caumes_homepage:
    path:     /
    defaults: { _controller: SCSebastienCaumesBundle:Work:index }

sc_sebastien_caumes_entity_detail:
    path:     /application/{slug}
    defaults: { _controller: SCSebastienCaumesBundle:Work:detail }


sc_sebastien_caumes_applications:
    path:   /applications
    defaults: { _controller: SCSebastienCaumesBundle:Work:showAll }

sc_sebastien_caumes_contact:
    path:   /contact
    defaults: { _controller: SCSebastienCaumesBundle:Contact:index }

logout:
    path: /logout