<?php

namespace SC\SebastienCaumesBundle\Entity;

/**
 * NewWorkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewWorkRepository extends \Doctrine\ORM\EntityRepository
{
}
